### ISSUE TITLE
Better composable XMLs support

### ISSUE THREAD

**Issue by alopatindev** [CasualX/format_xml#2]
I'd like to compose XMLs with functions. That works but solution is a bit noisy:

```rust
use format_xml::xml;

fn f(x: u8, y: u8) -> String {
    let result = xml! {
        <A>{x}</A>
        <B>{y}</B>
    }
    .to_string();
    result
}

fn main() {
    let x = xml! {
        <C>
            {f(1, 2)}
        </C>
        <C>
            {f(2, 1)}
        </C>
    }
    .to_string();
    println!("{}", x);
}
```

Removing intermediate `result` variable
```rust
fn f(x: u8, y: u8) -> String {
    xml! {
        <A>{x}</A>
        <B>{y}</B>
    }
    .to_string()
}
```
causes unobvious compiler error:
```
error: expected expression, found `.`
 --> src/main.rs:8:5
  |
8 |     .to_string()
  |     ^ expected expression

error[E0308]: mismatched types
 --> src/main.rs:4:5
  |
4 | /     xml! {
5 | |         <A>{x}</A>
6 | |         <B>{y}</B>
7 | |     }
  | |     ^
  | |     |
  | |_____expected `()`, found struct `std::fmt::Arguments`
  |       help: consider using a semicolon here
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Which can be fixed by wrapping `xml!` macros usage with `()` or `{}`:
```rust
fn f(x: u8, y: u8) -> String {
    (xml! {
        <A>{x}</A>
        <B>{y}</B>
    })
    .to_string()
}
```

Returning `std::fmt::Arguments` without constructing intermediate `String` would be even better, but I didn't find a way to satisfy borrow checker.

**Comment by CasualX** [comment]
Thanks for opening this issue!

The unobvious compile error is mysterious. The macro expands to

```rust
format_args !
          (concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!(concat!("", "<"), stringify ! (A)), ">"), "{}"),
                  "</"),
                  stringify ! (A)),
                  ">"),
                  "<"),
                  stringify ! (B)),
                  ">"),
                  "{}"),
                  "</"),
                  stringify ! (B)),
                  ">"),
           x, y)
```

When I manually replace the `xml!` invocation with that monstrosity then everything works as expected! I suspect a bug in Rust's parser interaction with macro output but I will need to do a deeper investigation,

In any case there's a better way to implement this. As you've noticed you _cannot_ return `std::fmt::Arguments` by value as they capture their arguments by reference. These are references to local variables in your function and won't be valid when your function returns.

For the specific purpose of composability I added the following syntax:

```rust
// Can also accept &mut std::fmt::Formatter directly
fn compose(f: &mut dyn std::fmt::Write, x: u8, y: u8) -> std::fmt::Result {
    f.write_fmt(xml! {
        <A>{x}</A>
        <B>{y}</B>
    })
}

fn main() {
    xml::println! {
        <C>
            |f| {compose(f, 1, 2)}
        </C>
        <C>
            |f| {compose(f, 1, 2)}
        </C>
    };
}
```

The idea is that you can pass the underlying formatter through just like if you would write an fmt trait implementation. This should be sufficient for composability. So instead of returning an Arguments structure, accept a formatter and write directly into it.

That said when I run this code I get `error[E0658]: attributes on expressions are experimental` because I try to wrap the resulting println's in a `#[inline(never)]` annotation to keep all the code generated for the formatting contained. No idea why I didn't catch this earlier. Using the `xml! { .. }.to_string()` does not have this problem.

**Comment by alopatindev** [comment]
Thanks! This `write_fmt`-based solution would be great to see in readme as well.

**Comment by CasualX** [comment]
Ok after some investigation the weird error you're getting for `xml!{}.to_string()` is apparently by design. The RFC which specifies this behavior can be found [here](https://github.com/rust-lang/rfcs/blob/master/text/0378-expr-macros.md). I found this RFC via this [thread](https://users.rust-lang.org/t/braces-square-brackets-and-parentheses-in-macro-call/9984).

What is happening is that a macro invoked with `{}` expands to a statement _if_ a statement is expected. If an expression is expected then macros invoked with `{}` expand to an expression. When applied to the example `xml!{}.to_string()` the parser takes `xml!{}` and turns it into a statement expecting a `()` type, but instead gets the `std::fmt::Arguments` type. Following a statement with `.` is also an error. Wrap the macro in parentheses: `(xml!{}).to_string()` and it goes back to working.

It's trivial to induce the same error with standard library macros: `concat!{""}.to_string()` gives the same error.

The compiler then attempts to provide suggestions which are unhelpful. It thinks to make your statement work that adding an explicit `;` will throw away the value properly resulting in `()`. Instead it should print a suggestion to use brackets or parentheses instead.

**Comment by alopatindev** [comment]
Thanks for the investigation! From the same thread:
> macros invoked with {} can be used as statements, where as macros invoked with [] or () are always expressions

This seems to be true, because this compiles as well:
```rust
fn f(x: u8, y: u8) -> String {
    xml!(
        <A>{x}</A>
        <B>{y}</B>
    )
    .to_string()
}
```

Maybe it's better to use `xml!(...)` (or `xml![...]`) instead of `xml! {...}` everywhere in the readme to make it hard to run into the weird error?

**Comment by CasualX** [comment]
Yeah I'm considering it. I really like the `{}` for multiline expressions but this potential confusion is problematic. I'm also considering using full statements in the examples instead of what I have now.

But this is for later. In the meantime I rewrote a bunch of code again (see `fresh` branch) related to utilities to format comma and space-delimited items.
